"""Strip/extract parity with the retired JS implementation (detector/wiki.js).

Fixtures were generated by running the JS stripWikitext/extractTagRegion on
live wikitext; the Python port must reproduce them byte-for-byte.
"""

import json
from pathlib import Path

import pytest

from wikidetect import wiki

FIXTURES = Path(__file__).parent / "fixtures" / "wikitext"
NAMES = sorted(p.stem for p in FIXTURES.glob("*.wikitext"))


@pytest.mark.parametrize("name", NAMES)
def test_extract_tag_region_parity(name):
    wt = (FIXTURES / f"{name}.wikitext").read_text()
    meta = json.loads((FIXTURES / f"{name}.meta.json").read_text())
    region, whole = wiki.extract_tag_region(wt, meta["label"])
    assert whole == meta["wholeArticle"]
    assert region == (FIXTURES / f"{name}.region.txt").read_text()


@pytest.mark.parametrize("name", NAMES)
def test_strip_wikitext_parity(name):
    region = (FIXTURES / f"{name}.region.txt").read_text()
    assert wiki.strip_wikitext(region) == (FIXTURES / f"{name}.stripped.txt").read_text()


def test_trim_to_sentence():
    text = "A first sentence. " * 60  # ~1080 chars
    out = wiki.trim_to_sentence(text, 500, 100)
    assert out.endswith(".")
    assert len(out) <= 500


def test_slug():
    assert wiki.slug("Ahmed Metani") == "ahmed-metani"
    assert wiki.slug("Târgoviște Princely Court!") == "t-rgovi-te-princely-court"


def test_from_url_or_title():
    assert wiki.from_url_or_title("https://en.wikipedia.org/wiki/Otto_Hahn#Legacy") == "Otto Hahn"
    assert wiki.from_url_or_title("Otto Hahn") == "Otto Hahn"
